set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.var/vim/bundle/Vundle.vim
call vundle#begin('~/.var/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'mileszs/ack.vim'

Bundle 'joonty/vdebug.git'
Bundle 'joonty/vim-phpqa.git'
Bundle "wookiehangover/jshint.vim"

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

colorscheme molokai

set backupdir=~/.var/vim/backup/
set directory=~/.var/vim/swap/

set shell=bash\ -l

set incsearch
set smartcase
set hlsearch
set ignorecase
set ruler
set number
set showcmd
set showmode

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set listchars=tab:\ \ ,trail:.
set list

set autoindent
set smartindent

" disable mouse
set mouse-=a

set foldlevelstart=99
set foldmethod=indent

imap ii <C-[>
cmap ii <C-[>

map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

map <PageUp> <F4>
map <PageDown> <F3>
map <End> <F2>
map <Home> <F5>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set splitbelow
set splitright

autocmd FileType php set syntax=php

if has("gui_macvim")

    set transparency=2

    autocmd BufRead,BufNewFile *.build set filetype=xml

    au BufRead,BufNewFile *.twig set filetype=htmljinja

    autocmd FileType php set omnifunc=phpcomplete#CompletePHP

    let g:phpqa_codesniffer_args = "--standard=Symfony2"
    let g:phpqa_messdetector_ruleset = "/Users/iainsaxon/.vim/phpmd-ruleset.xml"

    " If php-cs-fixer is in $PATH, you don't need to define line below
    let g:php_cs_fixer_path = "php-cs-fixer"  " define the path to the php-cs-fixer.phar
    let g:php_cs_fixer_level = "all"  " which level ?
    let g:php_cs_fixer_config = "sf21"  " configuration
    let g:php_cs_fixer_php_path = ""  " Path to PHP
    " let g:php_cs_fixer_fixers_list = ""  " List of fixers
    let g:php_cs_fixer_enable_default_mapping = 1  " Enable the mapping by default (<leader>pcd)
    let g:php_cs_fixer_dry_run = 0  " Call command with dry-run option
    let g:php_cs_fixer_verbose = 0  " Return the output of command if 1, else an inline information.

    autocmd FileType php inoremap <C-d> <ESC>:call PhpDocSingle()<CR>i
    autocmd FileType php nnoremap <C-d> :call PhpDocSingle()<CR>
    autocmd FileType php vnoremap <C-d> :call PhpDocRange()<CR>
    autocmd FileType twig set syntax=htmljinja

    map <C-n> :E<CR>

    let g:vdebug_options = {}
    let g:vdebug_options["ide_key"] = 'sublime.xdebug'
    let g:vdebug_options["continuous_mode"] = 1

    let g:user_zen_expandabbr_key = '<C-y>'
    let g:use_zen_complete_tag = 1

endif


